### ISSUE TITLE
[Bug]: SyntaxError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by giampaolo** [rstcheck/rstcheck#217]
### To Dos

- [X] I tested with the [latest released version](https://github.com/rstcheck/rstcheck/releases/latest).

- [X] I have checked the [issues](https://github.com/rstcheck/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Example Code (rst)

```rst
git ls-files '*.rst' | xargs rstcheck --config=pyproject.toml
```

...against psutil code base.
```


### Relevant log output

```Shell
2024-04-06T19:52:07.4410323Z make lint-rst
2024-04-06T19:52:07.4425054Z make[1]: Entering directory '/home/runner/work/psutil/psutil'
2024-04-06T19:52:07.8247347Z Traceback (most recent call last):
2024-04-06T19:52:07.8257753Z   File "/opt/hostedtoolcache/Python/3.12.2/x64/bin/rstcheck", line 5, in <module>
2024-04-06T19:52:07.8258871Z     from rstcheck._cli import main
2024-04-06T19:52:07.8260727Z   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/rstcheck/_cli.py", line 11, in <module>
2024-04-06T19:52:07.8263628Z     from rstcheck_core import _extras, config as config_mod, runner
2024-04-06T19:52:07.8265684Z   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/rstcheck_core/runner.py", line 13, in <module>
2024-04-06T19:52:07.8267086Z     from . import _sphinx, checker, config, types
2024-04-06T19:52:07.8268090Z   File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/rstcheck_core/checker.py", line 7, in <module>
2024-04-06T19:52:07.8268985Z     import doctest
2024-04-06T19:52:07.8269417Z SyntaxError: source code string cannot contain null bytes
```
```


### Description

Hi. I have rstcheck integrated as part of psutil CI pipeline. It suddenly started failing due to `SyntaxError: source code string cannot contain null bytes`
https://github.com/giampaolo/psutil/actions/runs/8583440387/job/23522647404

### Operating System

Linux

### Operating System Details

_No response_

### Python Version

3.12

### rstcheck Version

6.2.1 (CLI), 1.2.1 (core)

### Additional Context

_No response_

**Comment by Cielquan** [comment]
Sorry for the long silence. I hope I can take a deeper look at this soon.
